### ISSUE TITLE
【错误】每次启动都会这样报错

### ISSUE THREAD

**Issue by Noogear** [Ez4p1xEL/NoBuildPlus#5]
[17:07:52 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
        at org.bukkit.Location.deserialize(Location.java:1116) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at NoBuildPlus-1.3.6.jar/p1xel.nobuildplus.Storage.Worlds.upload(Worlds.java:35) ~[NoBuildPlus-1.3.6.jar:?]
        at NoBuildPlus-1.3.6.jar/p1xel.nobuildplus.Storage.Worlds.createWorldsFile(Worlds.java:30) ~[NoBuildPlus-1.3.6.jar:?]
        at NoBuildPlus-1.3.6.jar/p1xel.nobuildplus.NoBuildPlus.onLoad(NoBuildPlus.java:58) ~[NoBuildPlus-1.3.6.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:564) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:341) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by Ez4p1xEL** [comment]
插件能正常使用吗?

发一下完整的logs文件

**Comment by Noogear** [comment]
> 插件能正常使用吗?
> 
> 发一下完整的logs文件



> Owner

可以正常使用，只是这个报错有些莫名其妙，就在加载的时候有
[logs.txt](https://github.com/user-attachments/files/16710838/logs.txt)

**Comment by Noogear** [comment]
又发现一个BUG
![QQ_1724349242529](https://github.com/user-attachments/assets/0ab1b2e5-d76b-4e25-b0e5-6b0f5a84500e)
这边有个玻璃版？然后点一下可以拿下来，就开始疯狂报错
[17:53:06 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "replacement" is null
[17:53:06 WARN]:        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1058)
[17:53:06 WARN]:        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:1041)
[17:53:06 WARN]:        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1227)
[17:53:06 WARN]:        at java.base/java.lang.String.replaceAll(String.java:3111)
[17:53:06 WARN]:        at NoBuildPlus-1.3.6.jar//p1xel.nobuildplus.Listener.GUIManager.onClick(GUIManager.java:98)
[17:53:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor411.execute(Unknown Source)
[17:53:06 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:53:06 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:527)
[17:53:06 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyInventoryClick(OtherPluginsListenerProxy.java:478)
[17:53:06 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyNormalInventoryClick(OtherPluginsListenerProxy.java:452)
[17:53:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor370.execute(Unknown Source)
[17:53:06 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:53:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
[17:53:06 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60)
[17:53:06 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:53:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[17:53:06 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3247)
[17:53:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[17:53:06 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[17:53:06 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[17:53:06 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:53:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152)
[17:53:06 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190)
[17:53:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526)
[17:53:06 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338)
[17:53:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:53:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[17:53:07 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getContents()" because "gui" is null
[17:53:07 WARN]:        at NoBuildPlus-1.3.6.jar//p1xel.nobuildplus.Listener.GUIManager.updateFlag(GUIManager.java:274)
[17:53:07 WARN]:        at NoBuildPlus-1.3.6.jar//p1xel.nobuildplus.Storage.Worlds.setFlag(Worlds.java:101)
[17:53:07 WARN]:        at NoBuildPlus-1.3.6.jar//p1xel.nobuildplus.Listener.GUIManager.onClick(GUIManager.java:95)
[17:53:07 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor411.execute(Unknown Source)
[17:53:07 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:53:07 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.executeListener(OtherPluginsListenerProxy.java:527)
[17:53:07 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyInventoryClick(OtherPluginsListenerProxy.java:478)
[17:53:07 WARN]:        at Craftorithm-1.10.9.jar//com.github.yufiriamazenta.craftorithm.listener.OtherPluginsListenerProxy.proxyNormalInventoryClick(OtherPluginsListenerProxy.java:452)
[17:53:07 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor370.execute(Unknown Source)
[17:53:07 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:53:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
[17:53:07 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60)
[17:53:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:53:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[17:53:07 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3247)
[17:53:07 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[17:53:07 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[17:53:07 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[17:53:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:53:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152)
[17:53:07 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1555)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190)
[17:53:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1533)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1526)
[17:53:07 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1484)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1491)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338)
[17:53:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:53:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Ez4p1xEL** [comment]
这个菜单问题在新版本修复了

**Comment by Noogear** [comment]
> 这个菜单问题在新版本修复了

盔甲架放置判断权限的话可以使用EntityPlaceEvent，不知道对你有没有帮助
